### ISSUE TITLE
QALD format

### ISSUE THREAD

**Issue by jheinecke** [askplatypus/wikidata-simplequestions#11]
Hi,
thanks for this data!
I noticed that `annotated_wd_data_test_answerable.txt` contains 5621 questions, however `qald-format/annotated_wd_data_test.json` contains 5721 (`jq  ".questions[].query.answers" annotated_wd_data_test.json | grep entity`) Does the qald-format contain the same data as the `*_anwserable.txt` files ? Further, the qald data contains multiple answers to the questions (if applicable) but in the `*_anwserable.txt` files there is always exactly one question (and not always the same as in the qald-format files, e.g  _what is the film genre for snow falling on cedars?_ has as answers the entities
Q1054574,Q1257444, Q130232 and Q3072039 in `qald-format/annotated_wd_data_test.json` (and in wikidata.org) but Q1257444 in `annotated_wd_data_test.txt` (possibly old data from freebase ?)).
Concerning the `qald-format` directory: What is the difference between `annotated_wd_data_*_full.json` and `annotated_wd_data_*.json` (for instance `annotated_wd_data_train_full.json` is much much large as `annotated_wd_data_train.json`, for valid and test it is the opposite.

**Comment by D063520** [comment]
Hi,

there are different points here ...

> I noticed that annotated_wd_data_test_answerable.txt contains 5621 questions, however qald-format/annotated_wd_data_test.json contains 5721 (jq ".questions[].query.answers" annotated_wd_data_test.json | grep entity) Does the qald-format contain the same data as the *_anwserable.txt files ?

You are right there is something wrong. I updated the repo and also uploaded the qald script for the conversion. So it is easier to check mistakes.

>  Further, the qald data contains multiple answers to the questions (if applicable) but in the *_anwserable.txt files there is always exactly one question (and not always the same as in the qald-format files, e.g what is the film genre for snow falling on cedars? has as answers the entities
Q1054574,Q1257444, Q130232 and Q3072039 in qald-format/annotated_wd_data_test.json (and in wikidata.org) but Q1257444 in annotated_wd_data_test.txt (possibly old data from freebase ?)).

This is right. The answers in the QALD case are computed via the SPARQL query, that is considered the right representation of the question. The answer set of QALD format is always containing the one in the txt file. I noticed that the result set is sometimes very big. I limited the number of results to 100.

> Concerning the qald-format directory: What is the difference between annotated_wd_data_*_full.json and annotated_wd_data_*.json (for instance annotated_wd_data_train_full.json is much much large as annotated_wd_data_train.json, for valid and test it is the opposite.

can you check now with the new version

Thank you for pointing to these problems. I think they were introduced during the last pull request.
