### ISSUE TITLE
question on the files ends with 'answerable'

### ISSUE THREAD

**Issue by zhhongzhi** [askplatypus/wikidata-simplequestions#2]
This work is very interesting and helpful.
I have a question is that what's files ends with 'answerable' means?

`The files ending with "_full" contain only triples that are also in Wikidata.`
And there is no file ending with "_full". 

Thanks again, and merry Christmas!

**Comment by D063520** [comment]
Hi, 

sorry for the late relpy. So the files that end with "_ answerable" contains questions where a corresponding triple exists in Wikidata.

Salut
D063520
