### ISSUE TITLE
'answerable' questions are not answerable

### ISSUE THREAD

**Issue by graue70** [askplatypus/wikidata-simplequestions#3]
> The files ending with "_answerable" contain only triples that are also in Wikidata.

In the first few lines in `annotated_wd_data_test_answerable.txt`, there are several issues:

1. 'Which genre of album is harder.....faster?': different result (rock music vs. classic rock)
2. 'what city was alex golfis born in': fine
3. 'what film is by the writer phil hay?': would be fine, but the triple is incorrect in wikidata
4. 'Which equestrian was born in dublin?': There is no 'place of birth' for Mark Kyle in wikidata.
5. 'What is a tv action show?': `m/01htzx` (Action) is mapped to `Q11272426` (some church in the Ukraine)
6. 'what's akbar tandjung's ethnicity': The triple is not part of wikidata.
7. 'Which Swiss conductor's cause of death is myocardial infarction?': fine
8. 'where was padraic mcguinness's place of death': fine
9. 'Who influenced michael mcdowell?': The triple is not part of wikidata.
10. 'which military was involved in the second battle of fort fisher': The triple is not part of wikidata.

So, in these first ten lines, there are three or four correct entries, five which are not answerable and one where the mapping is incorrect.

Scaling that up would mean that I can trust about 40% of all the 'answerable' examples. That's not a lot and makes the dataset unusable in my opinion.

**Comment by D063520** [comment]
Hello,

as a first feedback .... the fact that the question is not answerable is not a problem of this dataset it is a plus in my opinion. The reason is that when you get questions in a real scenario many questions will not be answerable using data in the KB. A question answering system should be able to recognize this and say "I  don't know".

The mapping is clearly a problem. But it comes from the transition of Freebase to Wikidata ....

Salut
D063520

**Comment by D063520** [comment]
Mapping problems in:
1 . yes you are right, I'm not sure where this is coming from.
5. wrong mapping

6.  example of not answering (https://qanswer-frontend.univ-st-etienne.fr/qa/full?query=what%27s%20akbar%20tandjung%27s%20ethnicity&tags=%5B%5D&lang=en&kb=wikidata,openstreetmap)


For the non answerable you can generate the SPARQL query, execute it agains the SPARQL endpoint. If there is no result you need to replay "No Answer".

So I agree that there is some noise, but on the other hand you have thousands of questions you can train on.

Salut
D063520

**Comment by D063520** [comment]
Ok, I take all back. You were right. I replaced the files. I think the old ones were the non answerable in fact. I run all the queries against Wikidata and checked again which are answerable. The files are updated now. Thank you very much for noting that!
BTW the argument with non-answerable questions holds but for the complete file.
