### ISSUE TITLE
Data with String Label Version

### ISSUE THREAD

**Issue by xanhho** [askplatypus/wikidata-simplequestions#7]
Dear authors,

Thank you very much for your work.
Do you have a version of the data with explicitly the string label of the entity and property?
Like this:
Alex Golfis  \t	place of birth  \t	  Athens	\t what city was alex golfis born in
Instead of this:
Q16330302	 \t P19	\t  Q1524	\t what city was alex golfis born in

Thank you for your attention.

**Comment by D063520** [comment]
no, we do not have this. But this should not be difficult to do using some wikidata API. Here a query to retrive for example the label of the subject:

https://query.wikidata.org/#select%20%2a%20where%20%7B%0Awd%3AQ16330302%20rdfs%3Alabel%20%3Flabel%20.%0AFILTER%28lang%28%3Flabel%29%3D%22en%22%29%0A%7D

But wikidata query limits will probably not allow you to do this for the whole benchmark. So you have to put up your own SPARQL endpoint. Not sure about other APIs.

Salut
D063520

**Comment by xanhho** [comment]
Hi D063520,
Thank you for your reply.
I can retrieve the label string now.
I have another question, you said that: 
"Rxxx property identifiers encode the inverse property of the Wikidata property Pxxx. For example R19 encodes the properties "born here", i.e. the inverse of P19 ("birth place")."

Could you please explain more about "the inverse property of the Wikidata property".
For example, I have a property "P31 - instance of" on Wikidata, how do I get the R31 property?

Thank you for your support.

**Comment by D063520** [comment]
Ok,

if the triple is:

Q1 P1 Q2

then you should generate 

Q1 P1 ?

ie, the question asks for the object. Otherwise, i.e.

Q1 R1 Q2

the question asks for the subject, i.e.

? P1 Q2

This is meant by reverse

**Comment by xanhho** [comment]
Thank you for a very quick reply.
I understand like this: 
- If the triple is: Q1, P1, Q2, the question is generated from (Q1, P1, ?)

- If the triple is: Q1, R1, Q2, the question is generated from (?, R1, Q2). And R1 = P1 in this case.

Is it right?

**Comment by D063520** [comment]
yep

**Comment by xanhho** [comment]
Hi D063520,

I have tried to check the data, and it has a little different from what I understand here.
I understand: 
- If the triple is: Q1, R1, Q2, the question is generated from (?, R1, Q2). And R1 = P1 in this case.

The data:
- Line 3: Q16225521	R58	Q192979	what film is by the writer phil hay?
Q16225521 = ‘Phil Hay'
Q192979 = 'Clash of the Titans'
R58 = P58 = 'screenwriter'
The question is generated from (Q16225521, R58, ?)

- Line 6: Q1761	R19	Q6768445	Which equestrian was born in dublin?
Q1761 = ‘Dublin'
Q6768445 = ‘Mark Kyle'
R19 = P19 = 'place of birth'
The question is generated from (Q1761, R19, ?)

So I see the question in the triple (Q1, R1, Q2) is also generated from (Q1, R1, ?). 
Could you please help me clear this point?

Thank you for your support.

**Comment by Tpt** [comment]
Sorry for the late answer.

In SimpleQuestions all the "queries" should follow the pattern (s, p, ?) (i.e. you want to find the object(s) for a given subject in predicates). This works very well for Freebase where each predicate has also a reverse predicate. But it's not the case in Wikidata. It's why we introduced the "Rx" predicate to encode the reverse of the "Px" predicates. "(s, Rx, o)" means "(o, Px, s)".

So, to take your examples:

* Line 3: Q16225521 R58 Q192979 what film is by the writer phil hay?
Q16225521 = ‘Phil Hay'
Q192979 = 'Clash of the Titans'
P58 = 'screenwriter'
The expected query is (?, P58, Q16225521) that is encoded as it were "(Q16225521, R58, ?)".

* Line 6: Q1761 R19 Q6768445 Which equestrian was born in dublin?
Q1761 = ‘Dublin'
Q6768445 = ‘Mark Kyle'
P19 = 'place of birth'
The expected query is (?, P19, Q1761) that is encoded as it were "(Q1761, P19, ?)".

**Comment by Tpt** [comment]
Sorry for the late answer.

In SimpleQuestions all the "queries" should follow the pattern (s, p, ?) (i.e. you want to find the object(s) for a given subject in predicates). This works very well for Freebase where each predicate has also a reverse predicate. But it's not the case in Wikidata. It's why we introduced the "Rx" predicate to encode the reverse of the "Px" predicates. "(s, Rx, o)" means "(o, Px, s)".

So, to take your examples:

* Line 3: Q16225521 R58 Q192979 what film is by the writer phil hay?
Q16225521 = ‘Phil Hay'
Q192979 = 'Clash of the Titans'
P58 = 'screenwriter'
The expected query is (?, P58, Q16225521) that is encoded as it were "(Q16225521, R58, ?)".

* Line 6: Q1761 R19 Q6768445 Which equestrian was born in dublin?
Q1761 = ‘Dublin'
Q6768445 = ‘Mark Kyle'
P19 = 'place of birth'
The expected query is (?, P19, Q1761) that is encoded as it were "(Q1761, P19, ?)".

**Comment by xanhho** [comment]
Hi, 

Thank you for your clarification.
I got it now.
So, the version in the dataset has swapped s and o when comparing with the version in Freebase.

Thank you for your support.
