### ISSUE TITLE
Wrong entities in the qald-format directory

### ISSUE THREAD

**Issue by mdtux89** [askplatypus/wikidata-simplequestions#8]
It seems that the queries in the 'qald-format' directory point to the answer entities instead of the question entities in some cases. Eg., in the first example the query contains the link for Saving Shiloh rather than for Warner Bros.

**Comment by heraclex12** [comment]
not only qald-format, I think all files are facing this issue

**Comment by Tpt** [comment]
Hi! Sorry for this problem. Do you have an example?

**Comment by heraclex12** [comment]
Hi @Tpt 

Below is an example from the second row on `annotated_wd_data_train.txt` file
```Q12439	R19	Q6106580	who is a musician born in detroit```

 Q6106580 is currently labeled as J. Moss in wikidata. You can check it [here](https://www.wikidata.org/wiki/Q6106580)

**Comment by Tpt** [comment]
> Below is an example from the second row on annotated_wd_data_train.txt file
Q12439 R19 Q6106580 who is a musician born in detroit

It seems perfectly fine to me. `Q12439` is the entity that should be extracted from the question, `R19` the relation and `Q6106580` an expected response.

**Comment by mdtux89** [comment]
That’s why I said the qald-format is wrong. In the qald-format for you have the sparql below, where you the entity in the query is the answer entity instead of the entity for ‘detroit’. I fixed the dataset myself by correcting the answer entities with the question entities. I can share the fixed version if you want , but it should be easy for you to fix it.

SELECT ?x WHERE { ?x \u003chttp://www.wikidata.org/prop/direct/P19\u003e \u003chttp://www.wikidata.org/entity/Q6106580\u003e .  }

**Comment by Tpt** [comment]
Hi! Yes, I see the problem. Sorry. It would be amazing if you could share the fixed version with a pull request.

**Comment by mdtux89** [comment]
I created the pull request: https://github.com/askplatypus/wikidata-simplequestions/pull/10

In case you wanna double check how I fixed it, here's the script:

```
import os
import sys
import json

def load_split(original_path, qald_path, new_path):
    data = json.load(open(os.path.join(qald_path)))
    corrections = {}
    for line in open(os.path.join(original_path)):
        question_wd, _, answer_wd, utterance = line.split('\t')
        utterance = utterance.strip()
        corrections[utterance] = (question_wd, answer_wd)

    corrected = []
    for d in data['questions']:
        if d['question'] is not None and d['question'] != 'n/a':
            for item in d['question']:
                if item['language'] == 'en':
                    utterance = item['string'].strip()
                    if utterance in corrections:
                        question_wd, answer_wd = corrections[utterance]
                        d['query']['sparql'] = d['query']['sparql'].replace(answer_wd.lower(), question_wd)\
                                                                   .replace(answer_wd, question_wd)
        corrected.append(d)
    json.dump({'questions': corrected}, open(new_path, 'w'), indent=2)

load_split(sys.argv[1], sys.argv[2], sys.argv[3])

```

**Comment by Tpt** [comment]
Thank you so much! I just merged your change. It should be fixed now.
