### ISSUE TITLE
about mid_to_qid.tsv

### ISSUE THREAD

**Issue by cdhx** [askplatypus/wikidata-simplequestions#9]
I have three questions: 

1. how do you construct this mid_to_qid.tsv? is there any propery that can link freebase and wikidata?

2. what is the use of https://www.wikidata.org/wiki/Wikidata:WikiProject_Freebase/Mapping, it seems there are only thousands of mapping from freebase to wikidata

3. is there any way to convert a wikidata property to DBpedia?

I would really appreciate any help in this regard. Thanks!

**Comment by Tpt** [comment]
> how do you construct this mid_to_qid.tsv? is there any propery that can link freebase and wikidata?

https://www.wikidata.org/wiki/Property:P646

> what is the use of https://www.wikidata.org/wiki/Wikidata:WikiProject_Freebase/Mapping, it seems there are only thousands of mapping from freebase to wikidata

It's used for predicates, not for topics.

> is there any way to convert a wikidata property to DBpedia?

Yes, there is a mapping on Wikidata: https://www.wikidata.org/wiki/Property:P20#P1628

**Comment by cdhx** [comment]
thanks a lot !

**Comment by cdhx** [comment]
I still have 3 question:
1. I searched for triple which have property: https://www.wikidata.org/wiki/Property:P646，but only got 1.2M triple，in your mid_to_qid.tsv，there are 3.85M mapping between freebase and wikidata, I cannot figure out what others is

2. about P1628 property, which link wikidata property to other KB, I just find 568 triples contain this link, among that only 28 are link in dbpedia, seems not useful enough. How did you dealing with other relation from wikidata to dbpedia, or may be you just directly convert freebase to dbpedia, is there any way can do that?

3. seemes that there are only  1 mapping in mid_to_qid.tsv is map to a wikidata property (P915), others are all entity, how did you dealing with other relation from freebase to wikidata

Looking forward to your reply !
